#include "color_logic.h"

// TODO: Change to be generated by a script?
static int32_t colorWheelPosition(PaletteColor color)
{
    switch (color) {
    case COLOR_RED:
        return 0;
    case COLOR_RED_ORANGE:
        return 1;
    case COLOR_ORANGE:
        return 2;
    case COLOR_YELLOW_ORANGE:
        return 3;
    case COLOR_YELLOW:
        return 4;
    case COLOR_YELLOW_GREEN:
        return 5;
    case COLOR_GREEN:
        return 6;
    case COLOR_BLUE_GREEN:
        return 7;
    case COLOR_BLUE:
        return 8;
    case COLOR_BLUE_VIOLET:
        return 9;
    case COLOR_VIOLET:
        return 10;
    case COLOR_RED_VIOLET:
        return 11;
    case COLOR_CERISE:
        return 11;
    }

    return -1;
}

#define COLOR_WHEEL_SIZE 12

static bool hasColorPosition(const PaletteColor colors[], size_t colorCount,
                             int32_t wantedPosition)
{
    for (size_t i = 0; i < colorCount; i++) {
        if (colorWheelPosition(colors[i]) == wantedPosition) {
            return true;
        }
    }

    return false;
}

static int32_t wrappedPosition(int32_t position)
{
    while (position < 0) {
        position += COLOR_WHEEL_SIZE;
    }

    return position % COLOR_WHEEL_SIZE;
}

static bool hasComplementaryScheme(const PaletteColor colors[],
                                   size_t colorCount)
{
    for (size_t i = 0; i < colorCount; i++) {
        int32_t position = colorWheelPosition(colors[i]);
        int32_t oppositePosition = wrappedPosition(position + 6);

        if (hasColorPosition(colors, colorCount, oppositePosition)) {
            return true;
        }
    }

    return false;
}

static bool hasAnalogousScheme(const PaletteColor colors[], size_t colorCount)
{
    for (size_t i = 0; i < colorCount; i++) {
        int32_t position = colorWheelPosition(colors[i]);
        int32_t leftPosition = wrappedPosition(position - 1);
        int32_t rightPosition = wrappedPosition(position + 1);

        if (hasColorPosition(colors, colorCount, leftPosition) &&
            hasColorPosition(colors, colorCount, rightPosition)) {
            return true;
        }
    }

    return false;
}

static bool hasTriadicScheme(const PaletteColor colors[], size_t colorCount)
{
    for (size_t i = 0; i < colorCount; i++) {
        int32_t position = colorWheelPosition(colors[i]);
        int32_t secondPosition = wrappedPosition(position + 4);
        int32_t thirdPosition = wrappedPosition(position + 8);

        if (hasColorPosition(colors, colorCount, secondPosition) &&
            hasColorPosition(colors, colorCount, thirdPosition)) {
            return true;
        }
    }

    return false;
}

static bool hasSplitComplementaryScheme(const PaletteColor colors[],
                                        size_t colorCount)
{
    for (size_t i = 0; i < colorCount; i++) {
        int32_t position = colorWheelPosition(colors[i]);

        int32_t oppositePosition = wrappedPosition(position + 6);
        int32_t leftSplitPosition = wrappedPosition(oppositePosition - 1);
        int32_t rightSplitPosition = wrappedPosition(oppositePosition + 1);

        if (hasColorPosition(colors, colorCount, leftSplitPosition) &&
            hasColorPosition(colors, colorCount, rightSplitPosition)) {
            return true;
        }
    }

    return false;
}

ColorScheme judgeColorScheme(const PaletteColor colors[], size_t colorCount)
{
    if (colorCount < 2) {
        return COLOR_SCHEME_NONE;
    }

    if (hasTriadicScheme(colors, colorCount)) {
        return COLOR_SCHEME_TRIADIC;
    }

    if (hasSplitComplementaryScheme(colors, colorCount)) {
        return COLOR_SCHEME_SPLIT_COMPLEMENTARY;
    }

    if (hasComplementaryScheme(colors, colorCount)) {
        return COLOR_SCHEME_COMPLEMENTARY;
    }

    if (hasAnalogousScheme(colors, colorCount)) {
        return COLOR_SCHEME_ANALOGOUS;
    }

    return COLOR_SCHEME_NONE;
}